# Generated by Django 3.0.8 on 2020-08-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooblog', '0003_auto_20200813_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='post_date',
        ),
    ]
